# Generated by Django 4.1.4 on 2022-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-time_updated']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-time_updated']},
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
